services:
  telescopium:
    container_name: telescopium
    ports:
      - 61100:80
    volumes:
      - ~/Desktop/docker/universe/telescopium/dist/:/usr/share/nginx/html/
      - ~/Desktop/docker/universe/telescopium/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx
